#!/bin/bash

#Display lines containing the pattern “root” and 3 lines after them in the file /etc/passwd.

grep -A 3 "root" /etc/passwd

#Esto buscará líneas que contengan "raíz" en el archivo /etc/passwd y mostrará 3 líneas después de cada coincidencia. La -Aopción se utiliza para especificar el número de líneas que se mostrarán después del partido.
