#!/bin/bash
#Create a script that prints all possible combinations of two letters, except oo.

#Letters are lower cases, from a to z
#One combination per line
#The output should be alpha ordered, starting with aa
#Do not print oo
#Your script file should contain maximum 64 characters

#solucion 1
printf "%s\n" {a..z}{a..z} | grep -v "oo"

#solucion 2
echo {a..z}{a..z} | tr " " "\n" | grep -v "oo"
